# Generated by Django 4.0.4 on 2022-04-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=20)),
                ('object_name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('ar-SA', 'ar-SA'), ('de-DE', 'de-DE'), ('en-US', 'en-US'), ('ko-KR', 'ko-KR'), ('pt-BR', 'pt-BR'), ('en-IN', 'en-IN'), ('es-ES', 'es-ES'), ('zh-CN', 'zh-CN'), ('fr-CA', 'fr-CA'), ('it-IT', 'it-IT'), ('ru-RU', 'ru-RU'), ('hi-IN', 'hi-IN'), ('es-US', 'es-US'), ('en-AU', 'en-AU'), ('en-UK', 'en-UK'), ('fr-FR', 'fr-FR'), ('en-GB', 'en-GB'), ('ja-JP', 'ja-JP')], max_length=20)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_language', models.CharField(choices=[('ar-SA', 'ar-SA'), ('de-DE', 'de-DE'), ('en-US', 'en-US'), ('ko-KR', 'ko-KR'), ('pt-BR', 'pt-BR'), ('en-IN', 'en-IN'), ('es-ES', 'es-ES'), ('zh-CN', 'zh-CN'), ('fr-CA', 'fr-CA'), ('it-IT', 'it-IT'), ('ru-RU', 'ru-RU'), ('hi-IN', 'hi-IN'), ('es-US', 'es-US'), ('en-AU', 'en-AU'), ('en-UK', 'en-UK'), ('fr-FR', 'fr-FR'), ('en-GB', 'en-GB'), ('ja-JP', 'ja-JP')], max_length=20)),
                ('translated_json_file', models.FileField(blank=True, null=True, upload_to='')),
                ('translated_subtitle_file', models.FileField(blank=True, null=True, upload_to='')),
                ('translate_complete', models.BooleanField(default=False)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.mediafiles')),
            ],
        ),
    ]
