# Generated by Django 4.0.4 on 2022-04-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0003_rename_chvod_id_mediafiles_file_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafiles',
            options={'verbose_name': 'Media Files'},
        ),
    ]
