# Generated by Django 4.0.4 on 2022-04-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0004_alter_mediafiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafiles',
            options={'verbose_name': 'Media File'},
        ),
    ]
