# Generated by Django 4.0.4 on 2022-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0005_alter_mediafiles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafiles',
            name='status_note',
            field=models.CharField(default='Data Save', max_length=200),
        ),
        migrations.AddField(
            model_name='translatefile',
            name='status_note',
            field=models.CharField(default='Translate Data Save', max_length=200),
        ),
    ]
