# Generated by Django 4.0.4 on 2022-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0006_mediafiles_status_note_translatefile_status_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafiles',
            name='job_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
